"""Formal, colloquial and finance-mixed Indonesian reminder copy."""
COPY = {
    'id-formal': {
        'greeting': 'Selamat siang. Ini pengingat angsuran pembiayaan konsumen dalam simulasi. Apakah Anda bersedia melanjutkan?',
        'consent': 'Apakah kita boleh melanjutkan pengingat simulasi ini? Ya atau tidak?',
        'declined': 'Baik, pengingat saya hentikan.',
        'synthetic': 'Informasi simulasi: ',
        'question': 'Apakah ada pertanyaan, atau Anda ingin meminta panggilan kembali?',
        'fallback': 'Saya belum memiliki informasi terverifikasi mengenai hal itu. Apakah Anda ingin berbicara dengan petugas?',
        'difficulty': 'Saya memahami kesulitan pembayaran Anda. Saya tidak dapat menjanjikan penghapusan denda atau perpanjangan waktu. Apakah Anda ingin panggilan kembali?',
        'callback': 'Hari dan jam berapa yang Anda pilih untuk panggilan kembali simulasi?',
        'callback_saved': 'Preferensi panggilan kembali simulasi telah dicatat. Jadwal masih perlu dikonfirmasi petugas.',
        'escalation': 'Permintaan bantuan petugas dalam simulasi telah dicatat. Belum ada petugas yang dihubungi.',
        'confirm_paid': 'Anda menyatakan sudah membayar. Mohon konfirmasi; simulasi ini tidak dapat memverifikasi pembayaran.',
        'paid': 'Pernyataan Anda bahwa pembayaran sudah dilakukan telah dicatat. Pembayaran belum diverifikasi.',
        'confirm_time': 'Mohon konfirmasi waktu panggilan kembali: {value}.',
        'ended': 'Pengingat dihentikan. Tidak ada informasi tambahan yang dikumpulkan.',
        'unclear': 'Ucapan belum terdengar jelas. Periksa transkripsi atau ketik jawaban; data belum diperbarui.',
        'silent': 'Mikrofon hampir tidak merekam suara. Periksa indikator suara atau pilih mikrofon lain.',
        'tts': 'Suara balasan tidak tersedia. Silakan baca jawaban pada layar.',
    },
    'id-colloquial': {
        'greeting': 'Halo, ini demo pengingat cicilan, ya. Boleh kita lanjut?',
        'consent': 'Boleh lanjut demo pengingatnya? Ya atau nggak?',
        'declined': 'Oke, pengingatnya aku stop.',
        'synthetic': 'Ini contoh demo, ya: ',
        'question': 'Ada yang mau ditanyain, atau mau ditelepon lagi?',
        'fallback': 'Info itu belum bisa aku pastikan. Mau ngobrol sama petugas?',
        'difficulty': 'Paham, lagi susah bayar, ya. Aku nggak bisa janji hapus denda atau tambah waktu. Mau ditelepon lagi?',
        'callback': 'Enaknya ditelepon lagi hari apa, jam berapa?',
        'callback_saved': 'Oke, waktu pilihanmu sudah dicatat di demo. Petugas masih perlu konfirmasi jadwalnya.',
        'escalation': 'Permintaan ngobrol sama petugas sudah dicatat di demo. Belum ada yang dihubungi.',
        'confirm_paid': 'Udah bayar, ya? Tolong konfirmasi dulu; demo ini nggak bisa cek pembayaran.',
        'paid': 'Oke, aku catat kamu bilang sudah bayar. Pembayarannya belum dicek.',
        'confirm_time': 'Konfirmasi dulu waktu teleponnya: {value}.',
        'ended': 'Oke, pengingatnya stop. Nggak ada detail tambahan yang diambil.',
        'unclear': 'Belum kedengeran jelas. Cek teksnya atau ketik jawaban, ya; datanya belum berubah.',
        'silent': 'Mic hampir nggak nangkap suara. Cek indikator atau pilih mic lain, ya.',
        'tts': 'Suaranya belum tersedia. Baca jawaban di layar dulu, ya.',
    },
    'id-en-mixed': {
        'greeting': 'Halo, ini demo reminder cicilan. Boleh kita lanjut?',
        'consent': 'Boleh lanjut demo reminder-nya? Ya atau tidak?',
        'declined': 'Baik, reminder saya stop.',
        'synthetic': 'Info demo: ',
        'question': 'Ada pertanyaan soal payment, atau perlu callback?',
        'fallback': 'Info itu belum verified. Mau berbicara dengan petugas?',
        'difficulty': 'Saya paham cash flow sedang sulit. Saya tidak bisa menjanjikan fee waiver atau perpanjangan due date. Perlu callback?',
        'callback': 'Hari dan jam berapa yang cocok untuk callback?',
        'callback_saved': 'Preferensi callback dicatat dalam demo. Jadwal tetap perlu konfirmasi petugas.',
        'escalation': 'Request bantuan petugas dicatat dalam demo. Belum ada petugas yang dihubungi.',
        'confirm_paid': 'Payment sudah dilakukan, ya? Mohon konfirmasi; demo tidak bisa verify payment.',
        'paid': 'Saya catat pernyataan payment sudah dilakukan. Payment belum verified.',
        'confirm_time': 'Mohon konfirmasi callback time: {value}.',
        'ended': 'Reminder saya stop. Tidak ada detail tambahan yang dikumpulkan.',
        'unclear': 'Audio belum jelas. Review teks atau ketik reply; data belum berubah.',
        'silent': 'Mic hampir tidak merekam audio. Check indikator suara atau pilih mic lain.',
        'tts': 'Spoken reply belum tersedia. Silakan baca jawaban di layar.',
    },
}

TOPICS = {'cicilan': r'\bcicilan\b|\bangsuran\b|\binstallment\b', 'tenor': r'\btenor\b',
          'denda': r'\bdenda\b|\bpenalty\b|\blate fee\b', 'DP': r'\bdp\b|\bdown payment\b|\buang muka\b',
          'jatuh tempo': r'\bjatuh tempo\b|\bdue date\b', 'pembiayaan': r'\bpembiayaan\b|\bfinancing\b',
          'reminder': r'\bberapa\b|\bkapan\b|\bamount\b'}
