"""Conversational copy; business facts are retrieved separately from the KB."""
COPY = {
    'en': {
        'greeting': 'Hello. This is a synthetic life-insurance renewal reminder. May we continue? Please say yes or no.',
        'consent': 'May we continue with this demo reminder? Please say yes or no.',
        'declined': 'Understood. I will stop the reminder.',
        'synthetic': 'Synthetic demo information: ',
        'question': 'Would you like to discuss the reminder or request a callback?',
        'fallback': 'I do not have verified information for that. Would you like a human representative?',
        'difficulty': 'I understand that payment may be difficult. I cannot promise an extension or change your coverage. Would you like a callback?',
        'callback': 'What day and time would you prefer for a mock callback?',
        'callback_saved': 'Your mock callback preference is recorded. A coordinator must confirm the appointment.',
        'escalation': 'I recorded a mock human-assistance request. No representative has been contacted.',
        'confirm_paid': 'You said you already paid. Please confirm; this demo cannot verify a payment.',
        'paid': 'I noted your statement that you paid. This demo has not verified a payment or renewed a policy.',
        'confirm_time': 'Please confirm this callback preference: {value}.',
        'ended': 'I have stopped the reminder and will collect no further details.',
        'unclear': 'I could not reliably hear that. Please review the transcription or type your reply; no details were updated.',
        'silent': 'The microphone recorded almost no sound. Check the input meter or select another microphone.',
        'tts': 'Spoken output is unavailable. Please read the displayed reply.',
    },
    'fil': {
        'greeting': 'Magandang araw po. Paalala ito para sa pag-renew ng seguro sa buhay sa isang kathang-isip na halimbawa. Maaari po ba tayong magpatuloy?',
        'consent': 'Maaari po ba tayong magpatuloy sa halimbawang paalala? Opo o hindi po?',
        'declined': 'Sige po. Ititigil ko na ang paalala.',
        'synthetic': 'Kathang-isip na halimbawa: ',
        'question': 'May tanong po ba kayo, o gusto ninyong magpatawag muli?',
        'fallback': 'Wala po akong beripikadong impormasyon tungkol diyan. Gusto po ba ninyong makausap ang isang kinatawan?',
        'difficulty': 'Naiintindihan ko po na mahirap magbayad ngayon. Hindi ako makapangangako ng palugit o pagbabago sa saklaw ng seguro. Gusto po ba ninyong magpatawag muli?',
        'callback': 'Anong araw at oras po ninyo gustong magpatawag muli?',
        'callback_saved': 'Naitala ang gusto ninyong oras sa halimbawang kahilingan. Kailangan pa itong kumpirmahin ng tagapag-ugnay.',
        'escalation': 'Naitala ko po ang halimbawang kahilingang makausap ang kinatawan. Wala pang taong nakontak.',
        'confirm_paid': 'Sinabi ninyong nakapagbayad na. Pakikumpirma po; hindi kayang beripikahin ng halimbawang ito ang bayad.',
        'paid': 'Naitala ang sinabi ninyong nakapagbayad na. Hindi pa beripikado ang bayad at walang segurong na-renew dito.',
        'confirm_time': 'Pakikumpirma po ang oras na ito: {value}.',
        'ended': 'Itinigil ko na po ang paalala. Wala nang kukuning detalye.',
        'unclear': 'Hindi ko po malinaw na narinig. Pakisuri ang teksto o i-type ang sagot; walang detalyeng binago.',
        'silent': 'Halos walang tunog na naitala. Tingnan ang metro ng mikropono o pumili ng ibang mikropono.',
        'tts': 'Hindi magamit ang boses ngayon. Pakibasa po ang sagot sa screen.',
    },
    'fil-en': {
        'greeting': 'Hello po! Demo reminder ito para sa life-insurance renewal. Okay lang po bang magpatuloy?',
        'consent': 'Okay lang po bang ituloy ang demo reminder? Yes o hindi po?',
        'declined': 'Sige po, stop na natin ang reminder.',
        'synthetic': 'Demo lang po ito: ',
        'question': 'May question po ba kayo, o gusto ninyo ng callback?',
        'fallback': 'Wala po akong verified info tungkol diyan. Gusto po ba ninyong makausap ang isang representative?',
        'difficulty': 'Gets ko po, mahirap magbayad ngayon. Hindi ako makakapag-promise ng extension o coverage change. Gusto po ba ninyo ng callback?',
        'callback': 'Anong araw at oras po kayo available for a callback?',
        'callback_saved': 'Noted po ang preferred callback time sa demo. Kailangan pa itong i-confirm ng coordinator.',
        'escalation': 'Noted po ang demo request for a representative. Wala pa pong taong nakontak.',
        'confirm_paid': 'Paid na po kayo, tama? Paki-confirm po; hindi kayang i-verify ng demo ang payment.',
        'paid': 'Noted po na paid na, ayon sa sinabi ninyo. Hindi pa verified ang payment at walang policy na na-renew dito.',
        'confirm_time': 'Paki-confirm po ang callback time: {value}.',
        'ended': 'Stop na po ang reminder. Wala nang kukuning details.',
        'unclear': 'Hindi ko po malinaw na narinig. Paki-review ang text o i-type ang reply; walang details na binago.',
        'silent': 'Halos walang audio ang mic. Check po ang input meter o pumili ng ibang microphone.',
        'tts': 'Unavailable po ang spoken reply. Pakibasa muna ang sagot sa screen.',
    },
}

TOPICS = {'premium': r'\bpremium\b|\bhulog\b', 'policy': r'\bpolicy\b|\bpolisa\b',
          'beneficiary': r'\bbeneficiar[yi]\b|\bbenepisyaryo\b', 'rider': r'\brider\b',
          'lapse': r'\blapse\b|\bmapapaso\b', 'coverage': r'\bcoverage\b|\bsaklaw\b',
          'bank referral': r'\bbank referral\b|\bbangko\b', 'reminder': r'\bmagkano\b|\bkailan\b|\bdue\b|\bamount\b'}
